# Gains for individual right feedback
IR: &IR
  K_P: 3.0     # Gain for positional error
  K_O: 6.0   # Gain for angular error
  # Force admittance
  F_M: [2.5, 2.5, 2.5]
  F_D: [25, 25, 25]
  F_K: [0, 0, 0]
  # Torque admittance
  T_M: [1000, 1000, 1000]
  T_D: [500, 500, 500]
  T_K: [0, 0, 0]
# Gains for individual left feedback
IL:
  <<: *IR
# Gains for coordinated absolute feedback
CA:
  <<: *IR
# Gains for coordinated relative feedback
CR:
  <<: *IR
# Minimum error to take action
MIN_ACTION: [0.005, 0.017453]  # [lin, ang]  #deg2rad(1)
# Maximum deviation in target
MAX_DEVIATION: [0.500, 1.7453]  # [lin, ang]  #deg2rad(100)
