# Gains for individual right feedback
IR: &IR
  K_P: 3.0   # Gain for positional error
  K_O: 6.0   # Gain for angular error
# Gains for individual left feedback
IL:
  <<: *IR
# Minimum error to take action
MIN_ACTION: [0.005, 0.017453]   # [lin, ang]  #deg2rad(1)
# Maximum deviation in target
MAX_DEVIATION: [0.500, 1.7453]  # [lin, ang]  #deg2rad(100)
