<?xml version="1.0"?>
<package format="2">
  <name>yumift_controllers</name>
  <version>0.2.0</version>
  <description>
    The controller package
  </description>

  <maintainer email="sebastiano.fregnan@control.lth.se">Sebastiano Fregnan</maintainer>
  <license>MIT</license>

  <url type="repository">http://github.com/ilVecc/yumift</url>
  <author email="sebastiano.fregnan@control.lth.se">Sebastiano Fregnan</author>

  <buildtool_depend>catkin</buildtool_depend>
  <buildtool_depend>python3-setuptools</buildtool_depend>

  <exec_depend>rospy</exec_depend>
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>yumift_common</exec_depend>
  <exec_depend>yumift_msgs</exec_depend>
  <!-- Python dependencies -->
  <exec_depend>python3-pip</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python-numpy-quaternion-pip</exec_depend>

</package>
