###############################################################################
###   CLOSED LOOP INVERSE KINEMATICS
###############################################################################
CLIK:
  # Gains for individual right control
  IR:
    K_P: 2.0     # Gain for positional error
    K_O: 8.0   # Gain for angular error
  # Gains for individual right control
  IL:
    K_P: 2.0
    K_O: 8.0
  # Gains for coordinated absolute control
  CA:
    K_P: 2.0
    K_O: 4.0
  # Gains for coordinated relative control
  CR:
    K_P: 2.0
    K_O: 4.0
  # Minimum error to take action
  MIN_ACTION: [0.005, 0.017453]  # [lin, ang]  #deg2rad(1)
  # Maximum deviation in target
  MAX_DEVIATION: [0.500, 1.7453]  # [lin, ang]  #deg2rad(100)


###############################################################################
###   DIRECT FORCE FEEDBACK
###############################################################################
DFF:
  # Gains for individual right feedback
  IR:
    K_P: 2.0     # Gain for positional error
    K_O: 8.0   # Gain for angular error
    K_F: 0.5  # Gain for force feedback
    K_T: 1.5   # Gain for torque feedback
  # Gains for individual right feedback
  IL:
    K_P: 2.0
    K_O: 8.0
    K_F: 0.5
    K_T: 1.5
  # Gains for coordinated absolute feedback
  CA:
    K_P: 2.0
    K_O: 4.0
    K_F: 0.02
    K_T: 0.4
  # Gains for coordinated relative feedback
  CR:
    K_P: 2.0
    K_O: 4.0
    K_F: 0.02
    K_T: 0.4
  # Minimum error to take action
  MIN_ACTION: [0.005, 0.017453]  # [lin, ang]  #deg2rad(1)
  # Maximum deviation in target
  MAX_DEVIATION: [0.500, 1.7453]  # [lin, ang]  #deg2rad(100)


###############################################################################
###   ADMITTANCE WRENCH FEEDBACK
###############################################################################
ADM:
  # Gains for individual right admittances
  IR:
    K_P: 2.0     # Gain for positional error
    K_O: 8.0   # Gain for angular error
    F_M: [2.0, 2.0, 2.0]
    F_D: null  # critical damping by default --> D = sqrt(M*K)
    F_K: [50, 50, 50]
    T_M: [0.5, 0.5, 1.0]
    T_D: null
    T_K: [10, 10, 10]
  # Gains for individual left admittances
  IL:
    K_P: 2.0     # Gain for positional error
    K_O: 8.0   # Gain for angular error
    F_M: [2.0, 2.0, 2.0]
    F_D: null  # critical damping by default --> D = sqrt(M*K)
    F_K: [50, 50, 50]
    T_M: [0.5, 0.5, 1.0]
    T_D: null
    T_K: [10, 10, 10]
  # Gains for coordinated absolute admittances
  CA:
    K_P: 2.0
    K_O: 4.0
    F_M: [3, 3, 3]
    F_D: null
    F_K: [30, 30, 30]
    T_M: [10, 10, 2]
    T_D: null
    T_K: [20000, 20000, 2000]
  # Gains for coordinated relative admittances
  CR:
    K_P: 2.0
    K_O: 4.0
    F_M: [1000, 1000, 1000]
    F_D: null
    F_K: [10000, 10000, 10000]
    T_M: [10, 10, 2]
    T_D: null
    T_K: [20000, 20000, 2000]
  # Minimum error to take action
  MIN_ACTION: [0.005, 0.017453]  # [lin, ang]  #deg2rad(1)
  # Maximum deviation in target
  MAX_DEVIATION: [0.500, 1.7453]  # [lin, ang]  #deg2rad(100)
